"""add assigned_to to issues

Revision ID: 30ebfde58db6
Revises: caaaeac61dd6
Create Date: 2026-01-10 20:10:14.908782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ebfde58db6'
down_revision: Union[str, Sequence[str], None] = 'caaaeac61dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_issues_assigned_to'), 'issues', ['assigned_to'], unique=False)
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_assigned_to'), table_name='issues')
    op.drop_column('issues', 'assigned_to')
    # ### end Alembic commands ###
