"""add version column to issues

Revision ID: 3a6b0763e0b6
Revises: c1048a693357
Create Date: 2026-01-11 17:02:46.966146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6b0763e0b6'
down_revision: Union[str, Sequence[str], None] = 'c1048a693357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("issues",sa.Column("version", sa.Integer(), nullable=False, server_default="1"))
    op.alter_column("issues", "version", server_default=None)
    op.drop_constraint(op.f('issues_assigned_to_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_assigned_to_fkey'), 'issues', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_column('issues', 'version')
    # ### end Alembic commands ###
